# Generated by Django 4.2.7 on 2023-12-02 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('0ef2cae7-acf2-4238-9fd0-f0765cc5eab0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
