# Generated by Django 4.2.7 on 2023-12-02 12:08

from django.db import migrations

from apps.credit.models import PAYMENT_CHOICES

credits_list = [
    (3, 1.1, PAYMENT_CHOICES[1]),
    (6, 1.15, PAYMENT_CHOICES[1]),
    (12, 1.2, PAYMENT_CHOICES[1]),
    (12, 1.3, PAYMENT_CHOICES[0]),
    (24, 1.4, PAYMENT_CHOICES[1]),
    (24, 1.5, PAYMENT_CHOICES[0]),
    (36, 1.45, PAYMENT_CHOICES[1]),
    (36, 1.55, PAYMENT_CHOICES[0]),
]


def fill_credits(apps, schema_editor):
    CreditDescription = apps.get_model("credit", "CreditDescription")
    CreditDescription.objects.bulk_create([CreditDescription(**{"duration_in_month": m[0],
                                                                "rate_index": m[1],
                                                                "payment_type": m[2], })
                                           for m in credits_list])


class Migration(migrations.Migration):
    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_credits),
    ]
