# Generated by Django 4.2.7 on 2023-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20231204_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='one_off_current_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
