# Generated by Django 4.2.7 on 2023-12-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_credit_one_off_current_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='next_payout',
            field=models.DateTimeField(null=True),
        ),
    ]
